kernel-6.10.0-0.rc2.10.el10
* Mon Jun 10 2024 Patrick Talbert <ptalbert@redhat.com> [6.10.0-0.rc2.10.el10]
- clk: sifive: Do not register clkdevs for PRCI clocks (Samuel Holland)
- cifs: Don't advance the I/O iterator before terminating subrequest (David Howells)
- smb: client: fix deadlock in smb2_find_smb_tcon() (Enzo Matsumiya)
- HID: Ignore battery for ELAN touchscreens 2F2C and 4116 (Louis Dalibard)
- HID: i2c-hid: elan: fix reset suspend current leakage (Johan Hovold)
- dt-bindings: HID: i2c-hid: elan: add 'no-reset-on-power-off' property (Johan Hovold)
- dt-bindings: HID: i2c-hid: elan: add Elan eKTH5015M (Johan Hovold)
- dt-bindings: HID: i2c-hid: add dedicated Ilitek ILI2901 schema (Johan Hovold)
- input: Add support for "Do Not Disturb" (Aseda Aboagye)
- input: Add event code for accessibility key (Aseda Aboagye)
- hid: asus: asus_report_fixup: fix potential read out of bounds (Andrew Ballance)
- HID: logitech-hidpp: add missing MODULE_DESCRIPTION() macro (Jeff Johnson)
- HID: intel-ish-hid: fix endian-conversion (Arnd Bergmann)
- HID: nintendo: Fix an error handling path in nintendo_hid_probe() (Christophe JAILLET)
- HID: logitech-dj: Fix memory leak in logi_dj_recv_switch_to_dj_mode() (José Expósito)
- HID: core: remove unnecessary WARN_ON() in implement() (Nikita Zhandarovich)
- HID: nvidia-shield: Add missing check for input_ff_create_memless (Chen Ni)
- HID: intel-ish-hid: Fix build error for COMPILE_TEST (Zhang Lixu)
- modpost: do not warn about missing MODULE_DESCRIPTION() for vmlinux.o (Masahiro Yamada)
- kbuild: explicitly run mksysmap as sed script from link-vmlinux.sh (Richard Acayan)
- kconfig: remove wrong expr_trans_bool() (Masahiro Yamada)
- kconfig: doc: document behavior of 'select' and 'imply' followed by 'if' (Masahiro Yamada)
- kconfig: doc: fix a typo in the note about 'imply' (Masahiro Yamada)
- kconfig: gconf: give a proper initial state to the Save button (Masahiro Yamada)
- kconfig: remove unneeded code for user-supplied values being out of range (Masahiro Yamada)
- media: intel/ipu6: add csi2 port sanity check in notifier bound (Bingbu Cao)
- media: intel/ipu6: update the maximum supported csi2 port number to 6 (Bingbu Cao)
- media: mei: csi: Warn less verbosely of a missing device fwnode (Sakari Ailus)
- media: mei: csi: Put the IPU device reference (Sakari Ailus)
- media: intel/ipu6: fix the buffer flags caused by wrong parentheses (Bingbu Cao)
- media: intel/ipu6: Fix an error handling path in isys_probe() (Christophe JAILLET)
- media: intel/ipu6: Move isys_remove() close to isys_probe() (Christophe JAILLET)
- media: intel/ipu6: Fix some redundant resources freeing in ipu6_pci_remove() (Christophe JAILLET)
- media: Documentation: v4l: Fix ACTIVE route flag (Sakari Ailus)
- media: mgb4: Fix double debugfs remove (Martin Tůma)
- irqchip/gic-v3-its: Fix potential race condition in its_vlpi_prop_update() (Hagar Hemdan)
- irqchip/sifive-plic: Chain to parent IRQ after handlers are ready (Samuel Holland)
- irqchip/riscv-intc: Prevent memory leak when riscv_intc_init_common() fails (Sunil V L)
- x86/amd_nb: Check for invalid SMN reads (Yazen Ghannam)
- x86/kexec: Fix bug with call depth tracking (David Kaplan)
- perf/core: Fix missing wakeup when waiting for context reference (Haifeng Xu)
- locking/atomic: scripts: fix ${atomic}_sub_and_test() kerneldoc (Carlos Llamas)
- redhat/configs: fedora: Enable some drivers for IPU6 support (Hans de Goede)
- nilfs2: fix nilfs_empty_dir() misjudgment and long loop on I/O errors (Ryusuke Konishi)
- mm: fix xyz_noprof functions calling profiled functions (Suren Baghdasaryan)
- codetag: avoid race at alloc_slab_obj_exts (Thadeu Lima de Souza Cascardo)
- mm/hugetlb: do not call vma_add_reservation upon ENOMEM (Oscar Salvador)
- mm/ksm: fix ksm_zero_pages accounting (Chengming Zhou)
- mm/ksm: fix ksm_pages_scanned accounting (Chengming Zhou)
- kmsan: do not wipe out origin when doing partial unpoisoning (Alexander Potapenko)
- vmalloc: check CONFIG_EXECMEM in is_vmalloc_or_module_addr() (Cong Wang)
- mm: page_alloc: fix highatomic typing in multi-block buddies (Johannes Weiner)
- nilfs2: fix potential kernel bug due to lack of writeback flag waiting (Ryusuke Konishi)
- memcg: remove the lockdep assert from __mod_objcg_mlstate() (Sebastian Andrzej Siewior)
- mm: arm64: fix the out-of-bounds issue in contpte_clear_young_dirty_ptes (Barry Song)
- mm: huge_mm: fix undefined reference to `mthp_stats' for CONFIG_SYSFS=n (Barry Song)
- mm: drop the 'anon_' prefix for swap-out mTHP counters (Baolin Wang)
- gpio: add missing MODULE_DESCRIPTION() macros (Jeff Johnson)
- gpio: tqmx86: fix broken IRQ_TYPE_EDGE_BOTH interrupt type (Matthias Schiffer)
- gpio: tqmx86: store IRQ trigger type and unmask status separately (Matthias Schiffer)
- gpio: tqmx86: introduce shadow register for GPIO output value (Matthias Schiffer)
- gpio: tqmx86: fix typo in Kconfig label (Gregor Herburger)
- nvme: fix nvme_pr_* status code parsing (Weiwen Hu)
- nvme-fabrics: use reserved tag for reg read/write command (Chunguang Xu)
- null_blk: fix validation of block size (Andreas Hindborg)
- io_uring: fix possible deadlock in io_register_iowq_max_workers() (Hagar Hemdan)
- io_uring/io-wq: avoid garbage value of 'match' in io_wq_enqueue() (Su Hui)
- io_uring/napi: fix timeout calculation (Jens Axboe)
- io_uring: check for non-NULL file pointer in io_file_can_poll() (Jens Axboe)
- btrfs: protect folio::private when attaching extent buffer folios (Qu Wenruo)
- btrfs: fix leak of qgroup extent records after transaction abort (Filipe Manana)
- btrfs: fix crash on racing fsync and size-extending write into prealloc (Omar Sandoval)
- SUNRPC: Fix loop termination condition in gss_free_in_token_pages() (Chuck Lever)
- Revert "riscv: mm: accelerate pagefault when badaccess" (Palmer Dabbelt)
- riscv: fix overlap of allocated page and PTR_ERR (Nam Cao)
- KVM: s390x: selftests: Add shared zeropage test (David Hildenbrand)
- s390/crash: Do not use VM info if os_info does not have it (Alexander Gordeev)
- arm64/io: add constant-argument check (Arnd Bergmann)
- arm64: armv8_deprecated: Fix warning in isndep cpuhp starting process (Wei Li)
- platform/x86/amd/hsmp: Check HSMP support on AMD family of processors (Suma Hegde)
- platform/x86: dell-smbios: Simplify error handling (Armin Wolf)
- platform/x86: dell-smbios: Fix wrong token data in sysfs (Armin Wolf)
- platform/x86: yt2-1380: add CONFIG_EXTCON dependency (Arnd Bergmann)
- platform/x86: touchscreen_dmi: Use 2-argument strscpy() (Andy Shevchenko)
- platform/x86: touchscreen_dmi: Drop "silead,max-fingers" property (Hans de Goede)
- Input: silead - Always support 10 fingers (Hans de Goede)
- iommu/amd: Fix Invalid wait context issue (Vasant Hegde)
- iommu/amd: Check EFR[EPHSup] bit before enabling PPR (Vasant Hegde)
- iommu/amd: Fix workqueue name (Vasant Hegde)
- iommu: Return right value in iommu_sva_bind_device() (Lu Baolu)
- iommu/dma: Fix domain init (Robin Murphy)
- iommu/amd: Fix sysfs leak in iommu init (Kun(llfl))
- ata: pata_macio: Fix max_segment_size with PAGE_SIZE == 64K (Michael Ellerman)
- drm/komeda: remove unused struct 'gamma_curve_segment' (Dr. David Alan Gilbert)
- drm/vmwgfx: Don't memcmp equivalent pointers (Ian Forbes)
- drm/vmwgfx: remove unused struct 'vmw_stdu_dma' (Dr. David Alan Gilbert)
- drm/vmwgfx: Don't destroy Screen Target when CRTC is enabled but inactive (Ian Forbes)
- drm/vmwgfx: Standardize use of kibibytes when logging (Ian Forbes)
- drm/vmwgfx: Remove STDU logic from generic mode_valid function (Ian Forbes)
- drm/vmwgfx: 3D disabled should not effect STDU memory limits (Ian Forbes)
- drm/vmwgfx: Filter modes which exceed graphics memory (Ian Forbes)
- drm/panel: sitronix-st7789v: Add check for of_drm_get_panel_orientation (Chen Ni)
- drm/amdgpu/pptable: Fix UBSAN array-index-out-of-bounds (Tasos Sahanidis)
- drm/amd: Fix shutdown (again) on some SMU v13.0.4/11 platforms (Mario Limonciello)
- drm/xe/pf: Update the LMTT when freeing VF GT config (Michal Wajdeczko)
- scsi: ufs: mcq: Fix error output and clean up ufshcd_mcq_abort() (Chanwoo Lee)
- scsi: core: Handle devices which return an unusually large VPD page count (Martin K. Petersen)
- scsi: mpt3sas: Add missing kerneldoc parameter descriptions (Deming Wang)
- scsi: qedf: Set qed_slowpath_params to zero before use (Saurav Kashyap)
- scsi: qedf: Wait for stag work during unload (Saurav Kashyap)
- scsi: qedf: Don't process stag work during unload and recovery (Saurav Kashyap)
- scsi: sr: Fix unintentional arithmetic wraparound (Justin Stitt)
- scsi: core: alua: I/O errors for ALUA state transitions (Martin Wilck)
- scsi: mpi3mr: Use proper format specifier in mpi3mr_sas_port_add() (Nathan Chancellor)
- PCI: Revert the cfg_access_lock lockdep mechanism (Dan Williams)
- selftests: net: lib: set 'i' as local (Matthieu Baerts (NGI0))
- selftests: net: lib: avoid error removing empty netns name (Matthieu Baerts (NGI0))
- selftests: net: lib: support errexit with busywait (Matthieu Baerts (NGI0))
- net: ethtool: fix the error condition in ethtool_get_phy_stats_ethtool() (Su Hui)
- ipv6: fix possible race in __fib6_drop_pcpu_from() (Eric Dumazet)
- af_unix: Annotate data-race of sk->sk_shutdown in sk_diag_fill(). (Kuniyuki Iwashima)
- af_unix: Use skb_queue_len_lockless() in sk_diag_show_rqlen(). (Kuniyuki Iwashima)
- af_unix: Use skb_queue_empty_lockless() in unix_release_sock(). (Kuniyuki Iwashima)
- af_unix: Use unix_recvq_full_lockless() in unix_stream_connect(). (Kuniyuki Iwashima)
- af_unix: Annotate data-race of net->unx.sysctl_max_dgram_qlen. (Kuniyuki Iwashima)
- af_unix: Annotate data-races around sk->sk_sndbuf. (Kuniyuki Iwashima)
- af_unix: Annotate data-races around sk->sk_state in UNIX_DIAG. (Kuniyuki Iwashima)
- af_unix: Annotate data-race of sk->sk_state in unix_stream_read_skb(). (Kuniyuki Iwashima)
- af_unix: Annotate data-races around sk->sk_state in sendmsg() and recvmsg(). (Kuniyuki Iwashima)
- af_unix: Annotate data-race of sk->sk_state in unix_accept(). (Kuniyuki Iwashima)
- af_unix: Annotate data-race of sk->sk_state in unix_stream_connect(). (Kuniyuki Iwashima)
- af_unix: Annotate data-races around sk->sk_state in unix_write_space() and poll(). (Kuniyuki Iwashima)
- af_unix: Annotate data-race of sk->sk_state in unix_inq_len(). (Kuniyuki Iwashima)
- af_unix: Annodate data-races around sk->sk_state for writers. (Kuniyuki Iwashima)
- af_unix: Set sk->sk_state under unix_state_lock() for truly disconencted peer. (Kuniyuki Iwashima)
- net: wwan: iosm: Fix tainted pointer delete is case of region creation fail (Aleksandr Mishin)
- igc: Fix Energy Efficient Ethernet support declaration (Sasha Neftin)
- ice: map XDP queues to vectors in ice_vsi_map_rings_to_vectors() (Larysa Zaremba)
- ice: add flag to distinguish reset from .ndo_bpf in XDP rings config (Larysa Zaremba)
- ice: remove af_xdp_zc_qps bitmap (Larysa Zaremba)
- ice: fix reads from NVM Shadow RAM on E830 and E825-C devices (Jacob Keller)
- ice: fix iteration of TLVs in Preserved Fields Area (Jacob Keller)
- Revert "xsk: Document ability to redirect to any socket bound to the same umem" (Magnus Karlsson)
- Revert "xsk: Support redirect to any socket bound to the same umem" (Magnus Karlsson)
- bpf: Set run context for rawtp test_run callback (Jiri Olsa)
- bpf: Fix a potential use-after-free in bpf_link_free() (Cong Wang)
- bpf, devmap: Remove unnecessary if check in for loop (Thorsten Blum)
- libbpf: don't close(-1) in multi-uprobe feature detector (Andrii Nakryiko)
- bpf: Fix bpf_session_cookie BTF_ID in special_kfunc_set list (Jiri Olsa)
- selftests/bpf: fix inet_csk_accept prototype in test_sk_storage_tracing.c (Andrii Nakryiko)
- ptp: Fix error message on failed pin verification (Karol Kolacinski)
- net/sched: taprio: always validate TCA_TAPRIO_ATTR_PRIOMAP (Eric Dumazet)
- net/mlx5: Fix tainted pointer delete is case of flow rules creation fail (Aleksandr Mishin)
- net/mlx5: Always stop health timer during driver removal (Shay Drory)
- net/mlx5: Stop waiting for PCI if pci channel is offline (Moshe Shemesh)
- net: ethernet: mtk_eth_soc: handle dma buffer size soc specific (Frank Wunderlich)
- rtnetlink: make the "split" NLM_DONE handling generic (Jakub Kicinski)
- mptcp: count CLOSE-WAIT sockets for MPTCP_MIB_CURRESTAB (Jason Xing)
- tcp: count CLOSE-WAIT sockets for TCP_MIB_CURRESTAB (Jason Xing)
- selftests: hsr: add missing config for CONFIG_BRIDGE (Hangbin Liu)
- vxlan: Fix regression when dropping packets due to invalid src addresses (Daniel Borkmann)
- net: sched: sch_multiq: fix possible OOB write in multiq_tune() (Hangyu Hua)
- ionic: fix kernel panic in XDP_TX action (Taehee Yoo)
- net: phy: Micrel KSZ8061: fix errata solution not taking effect problem (Tristram Ha)
- net/smc: avoid overwriting when adjusting sock bufsizes (Wen Gu)
- octeontx2-af: Always allocate PF entries from low prioriy zone (Subbaraya Sundeep)
- net: tls: fix marking packets as decrypted (Jakub Kicinski)
- wifi: rtlwifi: Ignore IEEE80211_CONF_CHANGE_RETRY_LIMITS (Bitterblue Smith)
- wifi: mt76: mt7615: add missing chanctx ops (Johannes Berg)
- wifi: wilc1000: document SRCU usage instead of SRCU (Alexis Lothoré)
- Revert "wifi: wilc1000: set atomic flag on kmemdup in srcu critical section" (Alexis Lothoré)
- Revert "wifi: wilc1000: convert list management to RCU" (Alexis Lothoré)
- wifi: ath11k: move power type check to ASSOC stage when connecting to 6 GHz AP (Baochen Qiang)
- wifi: ath11k: fix WCN6750 firmware crash caused by 17 num_vdevs (Carl Huang)
- wifi: ath10k: fix QCOM_RPROC_COMMON dependency (Dmitry Baryshkov)
- wifi: ath11k: Fix error path in ath11k_pcic_ext_irq_config (Breno Leitao)
- wifi: mac80211: fix UBSAN noise in ieee80211_prep_hw_scan() (Dmitry Antipov)
- wifi: mac80211: correctly parse Spatial Reuse Parameter Set element (Lingbo Kong)
- wifi: mac80211: fix Spatial Reuse element size check (Lingbo Kong)
- wifi: iwlwifi: mvm: don't read past the mfuart notifcation (Emmanuel Grumbach)
- wifi: iwlwifi: mvm: Fix scan abort handling with HW rfkill (Ilan Peer)
- wifi: iwlwifi: mvm: check n_ssids before accessing the ssids (Miri Korenblit)
- wifi: iwlwifi: mvm: properly set 6 GHz channel direct probe option (Ayala Beker)
- wifi: iwlwifi: mvm: handle BA session teardown in RF-kill (Johannes Berg)
- wifi: iwlwifi: mvm: Handle BIGTK cipher in kek_kck cmd (Yedidya Benshimol)
- wifi: iwlwifi: mvm: remove stale STA link data during restart (Benjamin Berg)
- wifi: iwlwifi: dbg_ini: move iwl_dbg_tlv_free outside of debugfs ifdef (Shahar S Matityahu)
- wifi: iwlwifi: mvm: set properly mac header (Mordechay Goodstein)
- wifi: iwlwifi: mvm: revert gen2 TX A-MPDU size to 64 (Johannes Berg)
- wifi: iwlwifi: mvm: d3: fix WoWLAN command version lookup (Yedidya Benshimol)
- wifi: iwlwifi: mvm: fix a crash on 7265 (Emmanuel Grumbach)
- wifi: iwlwifi: mvm: always set the TWT IE offset (Shaul Triebitz)
- wifi: iwlwifi: mvm: don't initialize csa_work twice (Miri Korenblit)
- wifi: mac80211: pass proper link id for channel switch started notification (Aditya Kumar Singh)
- wifi: cfg80211: fix 6 GHz scan request building (Johannes Berg)
- wifi: mac80211: handle tasklet frames before stopping (Johannes Berg)
- wifi: mac80211: apply mcast rate only if interface is up (Johannes Berg)
- wifi: cfg80211: pmsr: use correct nla_get_uX functions (Lin Ma)
- wifi: cfg80211: Lock wiphy in cfg80211_get_station (Remi Pommarel)
- wifi: cfg80211: fully move wiphy work to unbound workqueue (Johannes Berg)
- wifi: cfg80211: validate HE operation element parsing (Johannes Berg)
- wifi: mac80211: Fix deadlock in ieee80211_sta_ps_deliver_wakeup() (Remi Pommarel)
- wifi: mac80211: mesh: init nonpeer_pm to active by default in mesh sdata (Nicolas Escande)
- wifi: mac80211: mesh: Fix leak of mesh_preq_queue objects (Nicolas Escande)
- lib/test_rhashtable: add missing MODULE_DESCRIPTION() macro (Jeff Johnson)
- net: dst_cache: add two DEBUG_NET warnings (Eric Dumazet)
- ila: block BH in ila_output() (Eric Dumazet)
- ipv6: sr: block BH in seg6_output_core() and seg6_input_core() (Eric Dumazet)
- net: ipv6: rpl_iptunnel: block BH in rpl_output() and rpl_input() (Eric Dumazet)
- ipv6: ioam: block BH from ioam6_output() (Eric Dumazet)
- vmxnet3: disable rx data ring on dma allocation failure (Matthias Stocker)
- net: phy: micrel: fix KSZ9477 PHY issues after suspend/resume (Tristram Ha)
- net/tcp: Don't consider TCP_CLOSE in TCP_AO_ESTABLISHED (Dmitry Safonov)
- net/ncsi: Fix the multi thread manner of NCSI driver (DelphineCCChiu)
- net: rps: fix error when CONFIG_RFS_ACCEL is off (Jason Xing)
- ax25: Replace kfree() in ax25_dev_free() with ax25_dev_put() (Duoming Zhou)
- ax25: Fix refcount imbalance on inbound connections (Lars Kellogg-Stedman)
- virtio_net: fix a spurious deadlock issue (Heng Qi)
- virtio_net: fix possible dim status unrecoverable (Heng Qi)
- ethtool: init tsinfo stats if requested (Vadim Fedorenko)
- MAINTAINERS: remove Peter Geis (Peter Geis)
- virtio_net: fix missing lock protection on control_buf access (Heng Qi)
- tomoyo: update project links (Tetsuo Handa)
- efi: Add missing __nocfi annotations to runtime wrappers (Ard Biesheuvel)
- efi: pstore: Return proper errors on UEFI failures (Guilherme G. Piccoli)
- efi/libstub: zboot.lds: Discard .discard sections (Nathan Chancellor)
Resolves: RHEL-29722

Signed-off-by: Patrick Talbert <ptalbert@redhat.com>